export const COUNTRIES = [
  'Romania',
  'Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola', 'Antigua si Barbuda',
  'Arabia Saudita', 'Argentina', 'Armenia', 'Australia', 'Austria', 'Azerbaidjan',
  'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgia', 'Belize',
  'Benin', 'Bhutan', 'Bolivia', 'Bosnia si Hertegovina', 'Botswana', 'Brazilia',
  'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi',
  'Cambodgia', 'Camerun', 'Canada', 'Capul Verde', 'Cehia', 'Ciad', 'Chile',
  'China', 'Cipru', 'Columbia', 'Comore', 'Congo', 'Coreea de Nord', 'Coreea de Sud',
  'Costa Rica', 'Croatia', 'Cuba',
  'Danemarca', 'Djibouti', 'Dominica',
  'Ecuador', 'Egipt', 'Elvetia', 'Emiratele Arabe Unite', 'Eritreea', 'Estonia', 'Eswatini', 'Etiopia',
  'Fiji', 'Filipine', 'Finlanda', 'Franta',
  'Gabon', 'Gambia', 'Georgia', 'Germania', 'Ghana', 'Grecia', 'Grenada', 'Guatemala',
  'Guineea', 'Guineea-Bissau', 'Guyana',
  'Haiti', 'Honduras', 'Hong Kong',
  'India', 'Indonezia', 'Iordania', 'Irak', 'Iran', 'Irlanda', 'Islanda', 'Israel', 'Italia',
  'Jamaica', 'Japonia',
  'Kazahstan', 'Kenya', 'Kirgizstan', 'Kiribati', 'Kosovo', 'Kuwait',
  'Laos', 'Lesotho', 'Letonia', 'Liban', 'Liberia', 'Libia', 'Liechtenstein', 'Lituania', 'Luxemburg',
  'Macao', 'Madagascar', 'Malaezia', 'Malawi', 'Maldive', 'Mali', 'Malta', 'Marea Britanie',
  'Maroc', 'Mauritania', 'Mauritius', 'Mexic', 'Micronezia', 'Moldova',
  'Monaco', 'Mongolia', 'Muntenegru', 'Mozambic', 'Myanmar',
  'Namibia', 'Nauru', 'Nepal', 'Nicaragua', 'Niger', 'Nigeria', 'Norvegia', 'Noua Zeelanda',
  'Olanda',
  'Pakistan', 'Palau', 'Panama', 'Papua Noua Guinee', 'Paraguay', 'Peru', 'Polonia',
  'Portugalia', 'Puerto Rico',
  'Qatar',
  'Republica Centrafricana', 'Republica Dominicana', 'Republica Macedonia de Nord',
  'Rusia', 'Rwanda',
  'Saint Kitts si Nevis', 'Saint Lucia', 'Samoa', 'San Marino', 'Sao Tome si Principe',
  'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Siria', 'Slovacia',
  'Slovenia', 'Somalia', 'Spania', 'Sri Lanka', 'Statele Unite ale Americii',
  'Sudan', 'Sudan de Sud', 'Suedia', 'Surinam',
  'Taiwan', 'Tajikistan', 'Tanzania', 'Thailanda', 'Timorul de Est', 'Togo',
  'Tonga', 'Trinidad si Tobago', 'Tunisia', 'Turcia', 'Turkmenistan', 'Tuvalu',
  'Ucraina', 'Uganda', 'Ungaria', 'Uruguay', 'Uzbekistan',
  'Vanuatu', 'Vatican', 'Venezuela', 'Vietnam',
  'Yemen',
  'Zambia', 'Zimbabwe',
]
