export const DOMAINS = [
  'Administratie publica', 'Agricultura', 'Alimentatie publica', 'Aparare nationala',
  'Arhitectura', 'Arte vizuale', 'Asigurari', 'Auto', 'Automatizari',
  'Aviatie',
  'Banci', 'Big Data', 'Biotehnologie',
  'Cercetare', 'Chimie', 'Cloud Computing', 'Comert', 'Comunicatii',
  'Confectii', 'Constructii', 'Consultanta', 'Contabilitate',
  'Cosmetice', 'Cultura',
  'Design', 'Diplomatie', 'Distributie', 'Drept',
  'E-commerce', 'Ecologie', 'Economie', 'Educatie', 'Electronica',
  'Electrotehnica', 'Energetica', 'Energii regenerabile',
  'Entertainment', 'Estetica',
  'Farmacie', 'Film', 'Finante', 'Fitness', 'Foresterie',
  'Gaming', 'Gastronomie', 'Geologie',
  'HoReCa', 'HR (Resurse umane)',
  'Imobiliare', 'Import-Export', 'Industria alimentara',
  'Industria auto', 'Industria lemnului', 'Industria textila',
  'Informatica', 'Inteligenta artificiala', 'Invatamant',
  'Journalism', 'Justitie',
  'Logistica',
  'Management', 'Marketing', 'Mecanica', 'Media', 'Medicina',
  'Mediu', 'Metalurgie', 'Meteorologie', 'Minerit', 'Muzica',
  'Naval', 'Nonprofit/ONG', 'Nutritie',
  'Petrol si gaze', 'Piscicultura', 'Poligrafie', 'Politica',
  'Productie', 'Publicitate',
  'Real estate', 'Relatii internationale', 'Relatii publice',
  'Retail', 'Robotica',
  'Sanatate', 'Securitate', 'Servicii sociale', 'Silvicultura',
  'Software', 'Sondaje', 'Sport', 'Startup',
  'Telecomunicatii', 'Textile', 'Traduceri', 'Transport', 'Turism', 'TV/Radio',
  'Urbanism',
  'Vanzari', 'Veterinar', 'Viticultura',
  'Web Development',
  'Zootehnie',
]
