import {
  Flame, Trophy, Music, Coffee, Tv, Mountain, Utensils, Plane,
  Wine, Fish, Dumbbell, TreePine, Dice1, Swords, Gamepad2,
  PartyPopper, BookOpen, Camera, Landmark, Tent, Dog, Bike,
  Target, Clapperboard, Palette, Code, Heart, Headphones,
  Snowflake, Car, Cat, Scroll, Sparkles, Church,
} from 'lucide-react'

export const HOBBY_OPTIONS = [
  { label: 'Gratar', icon: Flame },
  { label: 'Fotbal', icon: Trophy },
  { label: 'Muzica', icon: Music },
  { label: 'Cafea', icon: Coffee },
  { label: 'Filme', icon: Tv },
  { label: 'Drumetii', icon: Mountain },
  { label: 'Gatit', icon: Utensils },
  { label: 'Calatorii', icon: Plane },
  { label: 'Vin', icon: Wine },
  { label: 'Pescuit', icon: Fish },
  { label: 'Fitness', icon: Dumbbell },
  { label: 'Gradinarit', icon: TreePine },
  { label: 'Table', icon: Dice1 },
  { label: 'Barbut', icon: Dice1 },
  { label: 'Poker', icon: Swords },
  { label: 'Gaming', icon: Gamepad2 },
  { label: 'Dans', icon: PartyPopper },
  { label: 'Lectura', icon: BookOpen },
  { label: 'Fotografie', icon: Camera },
  { label: 'Politica', icon: Landmark },
  { label: 'Camping', icon: Tent },
  { label: 'Animale', icon: Dog },
  { label: 'Ciclism', icon: Bike },
  { label: 'Vanatoare', icon: Target },
  { label: 'Baschet', icon: Swords },
  { label: 'Teatru', icon: Clapperboard },
  { label: 'Arta', icon: Palette },
  { label: 'Tehnologie', icon: Code },
  { label: 'Voluntariat', icon: Heart },
  { label: 'Podcast', icon: Headphones },
  { label: 'Ski', icon: Snowflake },
  { label: 'Sah', icon: Swords },
  { label: 'Auto', icon: Car },
  { label: 'Anime', icon: Cat },
  { label: 'Istorie', icon: Scroll },
  { label: 'Cosmetice', icon: Palette },
  { label: 'Dezvoltare personala', icon: Sparkles },
  { label: 'Spiritualitate', icon: Sparkles },
  { label: 'Religie', icon: Church },
  { label: 'Natura', icon: TreePine },
]
