export const PROFESSIONS = [
  'Acar', 'Actor', 'Acupuncturist', 'Administrator', 'Administrator baze de date',
  'Administrator retea', 'Administrator sistem', 'Agent comercial', 'Agent de asigurari',
  'Agent de paza', 'Agent de politie', 'Agent de turism', 'Agent de vanzari',
  'Agent imobiliar', 'Agricultor', 'Agronom', 'Ajutor bucatar', 'Ambalator',
  'Ambulantier', 'Analist business', 'Analist de date', 'Analist financiar',
  'Analist programator', 'Analist de sisteme', 'Animator', 'Antrenor sportiv',
  'Apicultor', 'Aprozarist', 'Arbitru sportiv', 'Archeolog', 'Arhitect',
  'Arhitect de interior', 'Arhitect software', 'Arhivist', 'Armurier',
  'Artist plastic', 'Artist vizual', 'Asistent de cercetare', 'Asistent juridic',
  'Asistent manager', 'Asistent medical', 'Asistent social', 'Asistent veterinar',
  'Astronom', 'Auditor', 'Auditor financiar', 'Auditor intern', 'Avocat',
  'Bacteriolog', 'Barman', 'Bibliotecar', 'Bijutier', 'Biochimist',
  'Biofizician', 'Biolog', 'Biostatistician', 'Blogger', 'Botanist',
  'Broker', 'Broker de asigurari', 'Brutar', 'Bucatar',
  'Cameraman', 'Caricaturist', 'Cardiolog', 'Cartograf', 'Casier',
  'Chimist', 'Chirurg', 'Cioban', 'Coach', 'Coafor', 'Cofetar',
  'Comisar', 'Compozitor', 'Conductor tren', 'Confectioner',
  'Consilier de cariera', 'Consilier financiar', 'Consilier juridic',
  'Consilier personal', 'Consilier scolar', 'Consilier vanzari',
  'Constructor', 'Consultant', 'Consultant de afaceri', 'Consultant de imagine',
  'Consultant de management', 'Consultant fiscal', 'Consultant HR',
  'Consultant IT', 'Consultant marketing', 'Contabil', 'Controlor de calitate',
  'Controlor de trafic aerian', 'Copywriter', 'Coregraf', 'Cosmetician',
  'Creator de continut', 'Creator de moda', 'Criminalist', 'Croitor',
  'Curier',
  'Dansator', 'Decorator', 'Dentist', 'Dermatolog', 'Designer',
  'Designer de interioare', 'Designer de produs', 'Designer grafic',
  'Designer industrial', 'Designer UX/UI', 'Designer vestimentar',
  'Designer web', 'Detective', 'Dietetician', 'Diplomat', 'Director artistic',
  'Director comercial', 'Director executiv', 'Director financiar',
  'Director general', 'Director marketing', 'Director operational',
  'Director resurse umane', 'Director tehnic', 'Director vanzari',
  'Dirijor', 'Distribuitor', 'DJ', 'Dulgher',
  'Economist', 'Editor', 'Editor foto', 'Editor video', 'Educator',
  'Electrician', 'Endocrinolog', 'Epidemiolog', 'Esteticiana', 'Etnograf',
  'Expert contabil', 'Expert criminalist', 'Expert in securitate',
  'Explorator',
  'Farmacist', 'Fierar', 'Filolog', 'Filosof', 'Fitoterapeut',
  'Fizician', 'Fiziokinetoterapeut', 'Fizioterapeut', 'Florar',
  'Fotbalist', 'Fotograf', 'Fotoreporter', 'Frigotehnist',
  'Gastroenterolog', 'Geamgiu', 'Geofizician', 'Geograf', 'Geolog',
  'Geomatician', 'Gestionar', 'Ghid turistic', 'Ginecolog', 'Grafician',
  'Hairstylist', 'Hematolog', 'Hidrograf', 'Hidrolog',
  'Ilustrator', 'Imunolog', 'Infirmier', 'Informatician',
  'Inginer', 'Inginer agronom', 'Inginer chimist', 'Inginer civil',
  'Inginer constructor', 'Inginer de mediu', 'Inginer de retea',
  'Inginer de sunet', 'Inginer de sistem', 'Inginer de zgomot',
  'Inginer electric', 'Inginer electronist', 'Inginer energetic',
  'Inginer geodez', 'Inginer mecanic', 'Inginer mecatronic',
  'Inginer minier', 'Inginer petrolist', 'Inginer silvic',
  'Inginer software', 'Inginer textile', 'Inspector', 'Inspector fiscal',
  'Inspector scolar', 'Instalator', 'Instructor auto', 'Instructor sportiv',
  'Interpret', 'Investigator',
  'Jokey', 'Jurnalist', 'Judecator', 'Jurist',
  'Kinetoterapeut',
  'Laborant', 'Lacatus', 'Lector universitar', 'Legislator', 'Legumicultor',
  'Librar', 'Lingvist', 'Logoped', 'Logistician',
  'Macaragiu', 'Machiaj artist', 'Machinist', 'Manager', 'Manager de proiect',
  'Manager de produs', 'Manager hotel', 'Manager operational', 'Manager restaurant',
  'Manipulant', 'Marinar', 'Maseur', 'Matematician', 'Mecanic',
  'Mecanic auto', 'Mecanic aviatie', 'Mecatronic', 'Mediator', 'Medic',
  'Medic cardiolog', 'Medic de familie', 'Medic dentist', 'Medic generalist',
  'Medic internist', 'Medic legist', 'Medic neurolog', 'Medic oftalmolog',
  'Medic ORL', 'Medic pediatru', 'Medic psihiatru', 'Medic radiolog',
  'Medic sportiv', 'Medic veterinar', 'Merceolog', 'Meteorolog',
  'Microbiolog', 'Miner', 'Minerolog', 'Moasa', 'Montator',
  'Motostivuitorist', 'Muncitor', 'Muralist', 'Museograf', 'Muzician',
  'Navigator', 'Negociator', 'Neurochirurg', 'Neurolog', 'Notar',
  'Nutritationist',
  'Oceanograf', 'Ofiter', 'Oftalmolog', 'Oncolog', 'Operator',
  'Operator call center', 'Operator CNC', 'Operator de productie',
  'Operator video', 'Optician', 'Optometrist', 'Ortoped',
  'Ortoptist', 'Ospatar', 'ORL',
  'Paleontolog', 'Paramedic', 'Patiser', 'Patolog', 'Paznic',
  'Pedagog', 'Pediatru', 'Peisagist', 'Pensionar', 'Pescar',
  'Petrochimist', 'Pictor', 'Pilot', 'Pilot de drone', 'Pizzar',
  'Planificator', 'Pneumolog', 'Poet', 'Politist', 'Pomicultor',
  'Pompier', 'Portar', 'Postar', 'Preot', 'Presedinte',
  'Producator', 'Producator muzical', 'Producator TV', 'Profesor',
  'Profesor universitar', 'Programator', 'Proiectant', 'Procuror',
  'Protectionist', 'Psiholog', 'Psiholog clinic', 'Psihoterapeut',
  'Psihiatru', 'Publicist',
  'Rabin', 'Radiolog', 'Realizator TV', 'Receptioner', 'Redactor',
  'Regizor', 'Relationist public', 'Reporter', 'Restaurator', 'Reumatolog',
  'Rigger',
  'Salvator', 'Sculptor', 'Secretar', 'Scriitor', 'Scrum Master',
  'Silvicultor', 'Sociolog', 'Sofer', 'Sofer de TIR', 'Somelier',
  'Specialist HR', 'Specialist IT', 'Specialist marketing',
  'Specialist relatii publice', 'Specialist SEO', 'Specialist vanzari',
  'Statistician', 'Steward', 'Stilist', 'Stivuitorist',
  'Stomatolog', 'Strungar', 'Student', 'Subinginer', 'Sudor', 'Supervizor',
  'Tapistar', 'Taxonomist', 'Taximetrist', 'Teamlead', 'Tehnician',
  'Tehnician dentar', 'Tehnician laborator', 'Tehnician medical',
  'Tehnician radiolog', 'Terapeut', 'Terapeut ocupational', 'Tinichigiu',
  'Tipograf', 'Topograf', 'Toxicolog', 'Traducator', 'Trainer',
  'Trezorier', 'Tunar',
  'Urolog',
  'Valutar', 'Vanzator', 'Videograf', 'Viticultor', 'Vitrier',
  'Voluntar', 'Vopsitor',
  'Zoolog', 'Zootehinist',
]
