// All Romanian cities: 103 municipalities + 217 towns, alphabetically sorted
export const ROMANIAN_CITIES = [
  'Abrud', 'Adjud', 'Agnita', 'Aiud', 'Alba Iulia', 'Alesd', 'Alexandria',
  'Amara', 'Anina', 'Aninoasa', 'Arad', 'Ardud', 'Avrig', 'Azuga',
  'Babadag', 'Babeni', 'Bacau', 'Baicoi', 'Baia de Arama', 'Baia de Aries',
  'Baia Mare', 'Baia Sprie', 'Baile Govora', 'Baile Herculane',
  'Baile Olanesti', 'Baile Tusnad', 'Bailesti', 'Balan', 'Balcesti', 'Bals',
  'Baneasa', 'Baraolt', 'Barlad', 'Bechet', 'Beclean', 'Berbesti',
  'Beresti', 'Bicaz', 'Bistrita', 'Blaj', 'Bocsa', 'Boldesti-Scaeni',
  'Bolintin-Vale', 'Borsec', 'Botosani', 'Brad', 'Bragadiru', 'Braila',
  'Brasov', 'Breaza', 'Brezoi', 'Brosteni', 'Bucuresti', 'Budesti',
  'Buftea', 'Buhusi', 'Busteni', 'Buzau', 'Buzias',
  'Cajvana', 'Calan', 'Calafat', 'Calimesti', 'Calarasi', 'Campeni',
  'Campia Turzii', 'Campina', 'Campulung', 'Campulung Moldovenesc',
  'Caracal', 'Caransebes', 'Carei', 'Cavnic', 'Cehu Silvaniei',
  'Cernavoda', 'Chisineu-Cris', 'Chitila', 'Ciacova', 'Cisnadie',
  'Cluj-Napoca', 'Codlea', 'Comanesti', 'Constanta', 'Copsa Mica',
  'Corabia', 'Costesti', 'Covasna', 'Craiova', 'Cristuru Secuiesc',
  'Cugir', 'Curtea de Arges', 'Curtici',
  'Darabani', 'Darmanesti', 'Dej', 'Deta', 'Deva', 'Dolhasca', 'Dorohoi',
  'Dragasani', 'Draganesti-Olt', 'Drobeta-Turnu Severin', 'Dumbraveni',
  'Eforie',
  'Fagaras', 'Faget', 'Falticeni', 'Fetesti', 'Fieni', 'Filiasi',
  'Flamanzi', 'Focsani', 'Fundulea',
  'Galati', 'Gataia', 'Geoagiu', 'Gheorgheni', 'Gherla', 'Giurgiu',
  'Gura Humorului',
  'Harlau', 'Harsova', 'Hateg', 'Horezu', 'Huedin', 'Hunedoara', 'Husi',
  'Ianca', 'Iasi', 'Iernut', 'Ineu', 'Insuratei', 'Intorsura Buzaului',
  'Isaccea',
  'Jibou', 'Jimbolia',
  'Lehliu Gara', 'Lipova', 'Liteni', 'Livada', 'Ludus', 'Lugoj', 'Lupeni',
  'Macin', 'Magurele', 'Mangalia', 'Marasesti', 'Marghita', 'Medgidia',
  'Medias', 'Miercurea Ciuc', 'Mioveni', 'Mizil', 'Moinesti',
  'Moldova Noua', 'Moreni', 'Motru', 'Murfatlar',
  'Nadlac', 'Navodari', 'Negresti', 'Negresti-Oas', 'Negru Voda',
  'Nehoiu', 'Novaci', 'Nucet',
  'Ocna Mures', 'Ocna Sibiului', 'Ocnele Mari', 'Odobesti',
  'Odorheiu Secuiesc', 'Oltenita', 'Onesti', 'Oradea', 'Orastie',
  'Oravita', 'Orsova', 'Otelu Rosu', 'Otopeni', 'Ovidiu',
  'Panciu', 'Pantelimon', 'Pascani', 'Patarlagele', 'Pecica', 'Petrila',
  'Petrosani', 'Piatra Neamt', 'Piatra Olt', 'Pitesti', 'Ploiesti',
  'Plopeni', 'Podu Iloaiei', 'Pogoanele', 'Popesti-Leordeni', 'Potcoava',
  'Predeal', 'Pucioasa',
  'Racari', 'Radauti', 'Ramnicu Sarat', 'Ramnicu Valcea', 'Rasnov',
  'Recas', 'Reghin', 'Resita', 'Roman', 'Rosiorii de Vede', 'Rovinari',
  'Rupea',
  'Sacele', 'Saliste', 'Sangeorz-Bai', 'Sannicolau Mare', 'Santana',
  'Satu Mare', 'Saveni', 'Scornicesti', 'Sebes', 'Segarcea', 'Seini',
  'Sfantu Gheorghe', 'Sibiu', 'Sighetu Marmatiei', 'Sighisoara', 'Simeria',
  'Simleu Silvaniei', 'Sinaia', 'Siret', 'Slanic', 'Slanic Moldova',
  'Slatina', 'Slobozia', 'Solca', 'Somcuta Mare', 'Sovata', 'Stefanesti',
  'Stei', 'Strehaia', 'Suceava', 'Sulina',
  'Tandarei', 'Targoviste', 'Targu Bujor', 'Targu Carbunesti',
  'Targu Frumos', 'Targu Jiu', 'Targu Lapus', 'Targu Mures',
  'Targu Neamt', 'Targu Ocna', 'Targu Secuiesc', 'Tarnaveni', 'Tasnad',
  'Techirghiol', 'Tecuci', 'Timisoara', 'Tismana', 'Titu', 'Toplita',
  'Tulcea', 'Turceni', 'Turda', 'Turnu Magurele',
  'Ulmeni', 'Ungheni', 'Uricani', 'Urlati', 'Urziceni',
  'Valea lui Mihai', 'Valenii de Munte', 'Vaslui', 'Vatra Dornei',
  'Victoria', 'Videle', 'Viseu de Sus', 'Vlahita', 'Voluntari', 'Vulcan',
  'Zalau', 'Zarnesti', 'Zimnicea', 'Zlatna',
]
